services:
    bookmark-manager:
        container_name: bookmark-manager
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            DATABASE_URL: /data/bookmark.db
            API_BASE_URL: http://127.0.0.1:8000
            NUXT_PUBLIC_API_BASE_URL: http://127.0.0.1:8000
        ports:
            - "3000:3000"
            - "8000:8000"
        volumes:
            - ./data:/data
