services:
  shiori-keeper:
    container_name: shiori-keeper
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: /data/bookmarks.db
    ports:
      - "3033:3000"
      - "8044:8000"
    volumes:
      - ./data:/data
